language: python
stages:
  - deploy

jobs:
  include:
    # Deploy to PyPi if all tests pass and change was done on master.
    - stage: deploy
      name: "Deploy to PyPi"
      install: pip install -U pip setuptools wheel
      script: cat reporeleaser/version.py && sed -i "s/VERSION/$TRAVIS_TAG/" reporeleaser/version.py && cat reporeleaser/version.py 
      deploy: &pypi
        provider: pypi
        user: "$PYPIUSER"
        password: "$PYPIKEY"
        on:
          tags: true